import { DateTime } from 'luxon';
import { v4 as getUuid } from 'uuid';

import Transaction, { Category, TransactionType } from 'types/transaction';

export const transactions: Transaction[] = [
  {
    accountId: 'account-1',
    amount: 1822,
    datetime: '2024-05-06',
    id: '1',
    merchant: 'City Of Toronto Ferry',
    name: 'CITY OF TORONTO FERRY TORONTO ON',
    type: TransactionType.Debit,
    category: Category.Spending,
  },
  {
    accountId: 'account-1',
    amount: 1227,
    datetime: '2024-05-06',
    id: '2',
    merchant: 'Independent Cit',
    name: 'INDEPENDENT CIT TORONTO ON',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: '61c91b96-a24b-4a08-a8f6-1e99c6790be3',
    tag: 'Groceries',
  },
  {
    accountId: 'account-1',
    amount: 3702,
    datetime: '2024-05-06',
    id: '3',
    merchant: 'Independent Cit',
    name: 'INDEPENDENT CIT TORONTO ON',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: '61c91b96-a24b-4a08-a8f6-1e99c6790be3',
    tag: 'Groceries',
  },
  {
    accountId: 'account-1',
    amount: 33899,
    datetime: '2024-05-06',
    id: '4',
    merchant: 'Music Store',
    name: 'MUSIC STORE IN TORONTO ON',
    type: TransactionType.Debit,
    category: Category.Spending,
  },
  {
    accountId: 'account-1',
    amount: 2055,
    datetime: '2024-05-05',
    id: '5',
    merchant: 'Food Markets',
    name: 'FOOD MARKETS',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: '9a976493-a626-4722-92cf-ad1dc41d06dd',
    tag: 'Groceries',
  },
  {
    accountId: 'account-2',
    amount: 890,
    datetime: '2024-05-04',
    id: '6',
    merchant: 'Food Markets',
    name: 'FOOD MARKETS',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: '9a976493-a626-4722-92cf-ad1dc41d06dd',
    tag: 'Groceries',
  },
  {
    accountId: 'account-2',
    amount: 79,
    datetime: '2024-05-03',
    id: '8',
    merchant: 'Amazon',
    name: 'AWS',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: 'ff5700cd-1dff-4fa1-b946-bfd1127248bb',
    tag: 'Career & Productivity',
  },
  {
    accountId: 'account-2',
    amount: 87,
    datetime: '2024-05-03',
    id: '9',
    merchant: 'Amazon',
    name: 'AWS',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: 'ff5700cd-1dff-4fa1-b946-bfd1127248bb',
    tag: 'Career & Productivity',
  },
  {
    accountId: 'account-2',
    amount: 79,
    datetime: '2024-05-02',
    id: '13',
    merchant: 'Amazon',
    name: 'AWS',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: 'ff5700cd-1dff-4fa1-b946-bfd1127248bb',
    tag: 'Career & Productivity',
  },
  {
    accountId: 'account-2',
    amount: 699,
    datetime: '2024-05-02',
    id: '14',
    merchant: 'HelloFresh',
    name: 'HELLOFRESH',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: '8d77a633-b8c1-4422-9879-00a30c648f8e',
    tag: 'Groceries',
  },
  {
    accountId: 'account-2',
    amount: 8893,
    datetime: '2024-05-02',
    id: '15',
    merchant: 'HelloFresh',
    name: 'HELLOFRESH',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: '8d77a633-b8c1-4422-9879-00a30c648f8e',
    tag: 'Groceries',
  },
  {
    accountId: 'account-2',
    amount: 627,
    datetime: '2024-05-02',
    id: '16',
    merchant: 'Krispy Kreme',
    name: 'Krispy Kreme',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: 'e3a7cbcd-cf3f-48ca-9b48-db1be97c262e',
    tag: 'Restaurants',
  },
  {
    accountId: 'account-2',
    amount: 3025,
    datetime: '2024-05-02',
    id: '17',
    merchant: 'Insurance',
    name: 'INSURANCE',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: '3f31713b-f47b-48d1-bd64-243b23455da0',
    tag: 'Car',
  },
  {
    accountId: 'account-2',
    amount: 16495,
    datetime: '2024-05-02',
    id: '18',
    merchant: 'Insurance',
    name: 'INSURANCE',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: '3f31713b-f47b-48d1-bd64-243b23455da0',
    tag: 'Car',
  },
  {
    accountId: 'account-2',
    amount: 7458,
    datetime: '2024-05-02',
    id: '19',
    merchant: 'phone',
    name: 'PHONE',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: '4eaff9d3-8ad2-43db-8064-70a05fb915c0',
    tag: 'Phone',
  },
  {
    accountId: 'account-1',
    amount: 2291,
    datetime: '2024-05-02',
    id: '20',
    merchant: 'Home Hardware',
    name: 'HOME HARDWARE TORONTO ON',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: '5114f07a-2128-4327-ab42-c0d723ee3a41',
    tag: 'Guitar',
  },
  {
    accountId: 'account-2',
    amount: 1,
    datetime: '2024-05-01',
    id: '21',
    merchant: 'Google Cloud Services',
    name: 'GOOGLE CLOUD SERVICES',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: '8d20c530-6f7e-4b89-b87e-a49e84117ac7',
    tag: 'Career & Productivity',
  },
  {
    accountId: 'account-1',
    amount: 1402,
    datetime: '2024-05-01',
    id: '22',
    merchant: 'tv',
    name: 'tv',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: '2435c156-1a3e-44c8-bc42-0b9f17820a9d',
    tag: 'Entertainment',
  },
  {
    accountId: 'account-1',
    amount: 1348,
    datetime: '2024-05-01',
    id: '23',
    merchant: 'Independent Cit',
    name: 'INDEPENDENT CIT TORONTO ON',
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: '61c91b96-a24b-4a08-a8f6-1e99c6790be3',
    tag: 'Groceries',
  },
];

export const transactionsYearBeforeMay2024: Transaction[] = [
  getRandomizedTransaction({ month: '2024-04', tag: 'Entertainment' }),
  getRandomizedTransaction({ month: '2024-04', tag: 'Groceries' }),
  getRandomizedTransaction({ month: '2024-04', tag: 'Restaurants' }),
  getRandomizedTransaction({ month: '2024-04', tag: 'Transportation' }),
  getRandomizedTransaction({ month: '2024-03', tag: 'Entertainment' }),
  getRandomizedTransaction({ month: '2024-03', tag: 'Groceries' }),
  getRandomizedTransaction({ month: '2024-03', tag: 'Restaurants' }),
  getRandomizedTransaction({ month: '2024-03', tag: 'Transportation' }),
  getRandomizedTransaction({ month: '2024-02', tag: 'Entertainment' }),
  getRandomizedTransaction({ month: '2024-02', tag: 'Groceries' }),
  getRandomizedTransaction({ month: '2024-02', tag: 'Restaurants' }),
  getRandomizedTransaction({ month: '2024-02', tag: 'Transportation' }),
  getRandomizedTransaction({ month: '2024-01', tag: 'Entertainment' }),
  getRandomizedTransaction({ month: '2024-01', tag: 'Groceries' }),
  getRandomizedTransaction({ month: '2024-01', tag: 'Restaurants' }),
  getRandomizedTransaction({ month: '2024-01', tag: 'Transportation' }),
  getRandomizedTransaction({ month: '2023-12', tag: 'Entertainment' }),
  getRandomizedTransaction({ month: '2023-12', tag: 'Groceries' }),
  getRandomizedTransaction({ month: '2023-12', tag: 'Restaurants' }),
  getRandomizedTransaction({ month: '2023-12', tag: 'Transportation' }),
  getRandomizedTransaction({ month: '2023-11', tag: 'Entertainment' }),
  getRandomizedTransaction({ month: '2023-11', tag: 'Groceries' }),
  getRandomizedTransaction({ month: '2023-11', tag: 'Restaurants' }),
  getRandomizedTransaction({ month: '2023-11', tag: 'Transportation' }),
  getRandomizedTransaction({ month: '2023-10', tag: 'Entertainment' }),
  getRandomizedTransaction({ month: '2023-10', tag: 'Groceries' }),
  getRandomizedTransaction({ month: '2023-10', tag: 'Restaurants' }),
  getRandomizedTransaction({ month: '2023-10', tag: 'Transportation' }),
  getRandomizedTransaction({ month: '2023-09', tag: 'Entertainment' }),
  getRandomizedTransaction({ month: '2023-09', tag: 'Groceries' }),
  getRandomizedTransaction({ month: '2023-09', tag: 'Restaurants' }),
  getRandomizedTransaction({ month: '2023-09', tag: 'Transportation' }),
  getRandomizedTransaction({ month: '2023-08', tag: 'Entertainment' }),
  getRandomizedTransaction({ month: '2023-08', tag: 'Groceries' }),
  getRandomizedTransaction({ month: '2023-08', tag: 'Restaurants' }),
  getRandomizedTransaction({ month: '2023-08', tag: 'Transportation' }),
  getRandomizedTransaction({ month: '2023-07', tag: 'Entertainment' }),
  getRandomizedTransaction({ month: '2023-07', tag: 'Groceries' }),
  getRandomizedTransaction({ month: '2023-07', tag: 'Restaurants' }),
  getRandomizedTransaction({ month: '2023-07', tag: 'Transportation' }),
  getRandomizedTransaction({ month: '2023-06', tag: 'Entertainment' }),
  getRandomizedTransaction({ month: '2023-06', tag: 'Groceries' }),
  getRandomizedTransaction({ month: '2023-06', tag: 'Restaurants' }),
  getRandomizedTransaction({ month: '2023-06', tag: 'Transportation' }),
  getRandomizedTransaction({ month: '2023-05', tag: 'Entertainment' }),
  getRandomizedTransaction({ month: '2023-05', tag: 'Groceries' }),
  getRandomizedTransaction({ month: '2023-05', tag: 'Restaurants' }),
  getRandomizedTransaction({ month: '2023-05', tag: 'Transportation' }),
];

function getRandomizedTransaction({
  maxAmount = 100000,
  minAmount = 50000,
  month,
  tag,
}: {
  maxAmount?: number;
  minAmount?: number;
  month: string;
  tag: string;
}): Transaction {
  const parsedMonth = DateTime.fromISO(month);
  const monthSeed = parsedMonth.toUnixInteger();
  const tagSeed = toInt(tag);

  return getTransaction({
    amount: ((monthSeed * tagSeed) % (maxAmount - minAmount)) + minAmount,
    day: ((monthSeed + tagSeed) % 27) + 1,
    month,
    name: tag,
    tag,
  });
}

function getTransaction({
  amount,
  day,
  month,
  name,
  tag,
}: {
  amount: number;
  day: number;
  month: string;
  name: string;
  tag: string;
}): Transaction {
  return {
    accountId: 'account-1',
    amount,
    datetime: `${month}-${day.toString().padStart(2, '0')}`,
    id: getUuid(),
    merchant: name,
    name,
    type: TransactionType.Debit,
    category: Category.Spending,
    filteredBy: getUuid(),
    tag,
  };
}

function toInt(input: string): number {
  return new DataView(new TextEncoder().encode(input).buffer).getUint32(0);
}
